/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EventsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/tu_bs/ccc/contracting/edl/parser/antlr/internal/InternalEvents.tokens");
	}
}
