/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EventsUiModule extends AbstractEventsUiModule {

	public EventsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
