/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.events;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.edl.events.EventType#getComment <em>Comment</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.edl.events.EventType#getName <em>Name</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.edl.events.EventType#getEvents <em>Events</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEventType()
 * @model
 * @generated
 */
public interface EventType extends EObject
{
  /**
   * Returns the value of the '<em><b>Comment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' containment reference.
   * @see #setComment(AnnotationBlock)
   * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEventType_Comment()
   * @model containment="true"
   * @generated
   */
  AnnotationBlock getComment();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.edl.events.EventType#getComment <em>Comment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' containment reference.
   * @see #getComment()
   * @generated
   */
  void setComment(AnnotationBlock value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEventType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.edl.events.EventType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link de.tu_bs.ccc.contracting.edl.events.Event}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEventType_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

} // EventType
