/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.events;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.edl.events.Event#getElement <em>Element</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.edl.events.Event#isDefault <em>Default</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' attribute.
   * @see #setElement(String)
   * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEvent_Element()
   * @model
   * @generated
   */
  String getElement();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.edl.events.Event#getElement <em>Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' attribute.
   * @see #getElement()
   * @generated
   */
  void setElement(String value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(boolean)
   * @see de.tu_bs.ccc.contracting.edl.events.EventsPackage#getEvent_Default()
   * @model
   * @generated
   */
  boolean isDefault();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.edl.events.Event#isDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #isDefault()
   * @generated
   */
  void setDefault(boolean value);

} // Event
