/**
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.mapping;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Date</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see tu_bs.cs.isf.mapping.mapping.MappingPackage#getDate()
 * @model
 * @generated
 */
public interface Date extends Annotation
{
} // Date
