/**
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.mapping;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tu_bs.cs.isf.mapping.mapping.MappingPair#getPort <em>Port</em>}</li>
 *   <li>{@link tu_bs.cs.isf.mapping.mapping.MappingPair#getDiagram <em>Diagram</em>}</li>
 * </ul>
 *
 * @see tu_bs.cs.isf.mapping.mapping.MappingPackage#getMappingPair()
 * @model
 * @generated
 */
public interface MappingPair extends EObject
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' containment reference.
   * @see #setPort(ServiceMethod)
   * @see tu_bs.cs.isf.mapping.mapping.MappingPackage#getMappingPair_Port()
   * @model containment="true"
   * @generated
   */
  ServiceMethod getPort();

  /**
   * Sets the value of the '{@link tu_bs.cs.isf.mapping.mapping.MappingPair#getPort <em>Port</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' containment reference.
   * @see #getPort()
   * @generated
   */
  void setPort(ServiceMethod value);

  /**
   * Returns the value of the '<em><b>Diagram</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Diagram</em>' containment reference.
   * @see #setDiagram(CbcDiagram)
   * @see tu_bs.cs.isf.mapping.mapping.MappingPackage#getMappingPair_Diagram()
   * @model containment="true"
   * @generated
   */
  CbcDiagram getDiagram();

  /**
   * Sets the value of the '{@link tu_bs.cs.isf.mapping.mapping.MappingPair#getDiagram <em>Diagram</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Diagram</em>' containment reference.
   * @see #getDiagram()
   * @generated
   */
  void setDiagram(CbcDiagram value);

} // MappingPair
