/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.ui;

import com.google.inject.Injector;
import de.tu_bs.ccc.contracting.behavior.ui.internal.BehaviorActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BehaviorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BehaviorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BehaviorActivator activator = BehaviorActivator.getInstance();
		return activator != null ? activator.getInjector(BehaviorActivator.DE_TU_BS_CCC_CONTRACTING_BEHAVIOR) : null;
	}

}
