/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.behavior;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.Annotation#getRawText <em>Raw Text</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getAnnotation()
 * @model
 * @generated
 */
public interface Annotation extends EObject
{
  /**
   * Returns the value of the '<em><b>Raw Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Raw Text</em>' attribute.
   * @see #setRawText(String)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getAnnotation_RawText()
   * @model
   * @generated
   */
  String getRawText();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.Annotation#getRawText <em>Raw Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Raw Text</em>' attribute.
   * @see #getRawText()
   * @generated
   */
  void setRawText(String value);

} // Annotation
