/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.behavior;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage
 * @generated
 */
public interface BehaviorFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BehaviorFactory eINSTANCE = de.tu_bs.ccc.contracting.behavior.impl.BehaviorFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  BehaviorModel createBehaviorModel();

  /**
   * Returns a new object of class '<em>Behavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Behavior</em>'.
   * @generated
   */
  Behavior createBehavior();

  /**
   * Returns a new object of class '<em>Signal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Signal</em>'.
   * @generated
   */
  Signal createSignal();

  /**
   * Returns a new object of class '<em>Signal Signature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Signal Signature</em>'.
   * @generated
   */
  SignalSignature createSignalSignature();

  /**
   * Returns a new object of class '<em>Event Binding</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Binding</em>'.
   * @generated
   */
  EventBinding createEventBinding();

  /**
   * Returns a new object of class '<em>Event Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Trigger</em>'.
   * @generated
   */
  EventTrigger createEventTrigger();

  /**
   * Returns a new object of class '<em>Event On If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event On If</em>'.
   * @generated
   */
  EventOnIf createEventOnIf();

  /**
   * Returns a new object of class '<em>Method Signature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method Signature</em>'.
   * @generated
   */
  MethodSignature createMethodSignature();

  /**
   * Returns a new object of class '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event</em>'.
   * @generated
   */
  Event createEvent();

  /**
   * Returns a new object of class '<em>Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation</em>'.
   * @generated
   */
  Operation createOperation();

  /**
   * Returns a new object of class '<em>Standard Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Standard Operation</em>'.
   * @generated
   */
  StandardOperation createStandardOperation();

  /**
   * Returns a new object of class '<em>Var Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Decl</em>'.
   * @generated
   */
  VarDecl createVarDecl();

  /**
   * Returns a new object of class '<em>Refable Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Refable Type</em>'.
   * @generated
   */
  RefableType createRefableType();

  /**
   * Returns a new object of class '<em>Specification Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Specification Block</em>'.
   * @generated
   */
  SpecificationBlock createSpecificationBlock();

  /**
   * Returns a new object of class '<em>Contract Pair</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contract Pair</em>'.
   * @generated
   */
  ContractPair createContractPair();

  /**
   * Returns a new object of class '<em>Requires</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Requires</em>'.
   * @generated
   */
  Requires createRequires();

  /**
   * Returns a new object of class '<em>Ensures</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ensures</em>'.
   * @generated
   */
  Ensures createEnsures();

  /**
   * Returns a new object of class '<em>FState Graph</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FState Graph</em>'.
   * @generated
   */
  FStateGraph createFStateGraph();

  /**
   * Returns a new object of class '<em>FState</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FState</em>'.
   * @generated
   */
  FState createFState();

  /**
   * Returns a new object of class '<em>FTransition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FTransition</em>'.
   * @generated
   */
  FTransition createFTransition();

  /**
   * Returns a new object of class '<em>FTrigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FTrigger</em>'.
   * @generated
   */
  FTrigger createFTrigger();

  /**
   * Returns a new object of class '<em>FEvent On If</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FEvent On If</em>'.
   * @generated
   */
  FEventOnIf createFEventOnIf();

  /**
   * Returns a new object of class '<em>Broadcast</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Broadcast</em>'.
   * @generated
   */
  Broadcast createBroadcast();

  /**
   * Returns a new object of class '<em>FGuard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FGuard</em>'.
   * @generated
   */
  FGuard createFGuard();

  /**
   * Returns a new object of class '<em>FType Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FType Ref</em>'.
   * @generated
   */
  FTypeRef createFTypeRef();

  /**
   * Returns a new object of class '<em>FInteger Interval</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FInteger Interval</em>'.
   * @generated
   */
  FIntegerInterval createFIntegerInterval();

  /**
   * Returns a new object of class '<em>FType</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FType</em>'.
   * @generated
   */
  FType createFType();

  /**
   * Returns a new object of class '<em>FArray Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FArray Type</em>'.
   * @generated
   */
  FArrayType createFArrayType();

  /**
   * Returns a new object of class '<em>FType Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FType Def</em>'.
   * @generated
   */
  FTypeDef createFTypeDef();

  /**
   * Returns a new object of class '<em>FStruct Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FStruct Type</em>'.
   * @generated
   */
  FStructType createFStructType();

  /**
   * Returns a new object of class '<em>FUnion Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FUnion Type</em>'.
   * @generated
   */
  FUnionType createFUnionType();

  /**
   * Returns a new object of class '<em>FExpression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FExpression</em>'.
   * @generated
   */
  FExpression createFExpression();

  /**
   * Returns a new object of class '<em>FQualified Element Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FQualified Element Ref</em>'.
   * @generated
   */
  FQualifiedElementRef createFQualifiedElementRef();

  /**
   * Returns a new object of class '<em>FDouble Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FDouble Constant</em>'.
   * @generated
   */
  FDoubleConstant createFDoubleConstant();

  /**
   * Returns a new object of class '<em>FFloat Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FFloat Constant</em>'.
   * @generated
   */
  FFloatConstant createFFloatConstant();

  /**
   * Returns a new object of class '<em>FInteger Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FInteger Constant</em>'.
   * @generated
   */
  FIntegerConstant createFIntegerConstant();

  /**
   * Returns a new object of class '<em>FBoolean Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FBoolean Constant</em>'.
   * @generated
   */
  FBooleanConstant createFBooleanConstant();

  /**
   * Returns a new object of class '<em>FString Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FString Constant</em>'.
   * @generated
   */
  FStringConstant createFStringConstant();

  /**
   * Returns a new object of class '<em>FMap Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FMap Type</em>'.
   * @generated
   */
  FMapType createFMapType();

  /**
   * Returns a new object of class '<em>FField</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FField</em>'.
   * @generated
   */
  FField createFField();

  /**
   * Returns a new object of class '<em>FDeclaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FDeclaration</em>'.
   * @generated
   */
  FDeclaration createFDeclaration();

  /**
   * Returns a new object of class '<em>FTyped Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FTyped Element</em>'.
   * @generated
   */
  FTypedElement createFTypedElement();

  /**
   * Returns a new object of class '<em>FArgument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FArgument</em>'.
   * @generated
   */
  FArgument createFArgument();

  /**
   * Returns a new object of class '<em>FConstant Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FConstant Def</em>'.
   * @generated
   */
  FConstantDef createFConstantDef();

  /**
   * Returns a new object of class '<em>FInitializer Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FInitializer Expression</em>'.
   * @generated
   */
  FInitializerExpression createFInitializerExpression();

  /**
   * Returns a new object of class '<em>FInitializer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FInitializer</em>'.
   * @generated
   */
  FInitializer createFInitializer();

  /**
   * Returns a new object of class '<em>FCompound Initializer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FCompound Initializer</em>'.
   * @generated
   */
  FCompoundInitializer createFCompoundInitializer();

  /**
   * Returns a new object of class '<em>FField Initializer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FField Initializer</em>'.
   * @generated
   */
  FFieldInitializer createFFieldInitializer();

  /**
   * Returns a new object of class '<em>FBracket Initializer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FBracket Initializer</em>'.
   * @generated
   */
  FBracketInitializer createFBracketInitializer();

  /**
   * Returns a new object of class '<em>FElement Initializer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FElement Initializer</em>'.
   * @generated
   */
  FElementInitializer createFElementInitializer();

  /**
   * Returns a new object of class '<em>Detail Code</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Detail Code</em>'.
   * @generated
   */
  DetailCode createDetailCode();

  /**
   * Returns a new object of class '<em>Annotation Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation Block</em>'.
   * @generated
   */
  AnnotationBlock createAnnotationBlock();

  /**
   * Returns a new object of class '<em>Annotation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Annotation</em>'.
   * @generated
   */
  Annotation createAnnotation();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>FBinary Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FBinary Operation</em>'.
   * @generated
   */
  FBinaryOperation createFBinaryOperation();

  /**
   * Returns a new object of class '<em>FUnary Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FUnary Operation</em>'.
   * @generated
   */
  FUnaryOperation createFUnaryOperation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BehaviorPackage getBehaviorPackage();

} //BehaviorFactory
