/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.behavior;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Detail Code</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.DetailCode#getLines <em>Lines</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.DetailCode#isUsed <em>Used</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getDetailCode()
 * @model
 * @generated
 */
public interface DetailCode extends EObject
{
  /**
   * Returns the value of the '<em><b>Lines</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lines</em>' attribute list.
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getDetailCode_Lines()
   * @model unique="false"
   * @generated
   */
  EList<String> getLines();

  /**
   * Returns the value of the '<em><b>Used</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Used</em>' attribute.
   * @see #setUsed(boolean)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getDetailCode_Used()
   * @model
   * @generated
   */
  boolean isUsed();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.DetailCode#isUsed <em>Used</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Used</em>' attribute.
   * @see #isUsed()
   * @generated
   */
  void setUsed(boolean value);

} // DetailCode
