/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.behavior;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FBoolean Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.FBooleanConstant#isVal <em>Val</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFBooleanConstant()
 * @model
 * @generated
 */
public interface FBooleanConstant extends FExpression
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(boolean)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFBooleanConstant_Val()
   * @model
   * @generated
   */
  boolean isVal();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.FBooleanConstant#isVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #isVal()
   * @generated
   */
  void setVal(boolean value);

} // FBooleanConstant
