/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.behavior;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FType Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.FTypeRef#getPredefined <em>Predefined</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.FTypeRef#getDerived <em>Derived</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.FTypeRef#getInterval <em>Interval</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFTypeRef()
 * @model
 * @generated
 */
public interface FTypeRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Predefined</b></em>' attribute.
   * The literals are from the enumeration {@link de.tu_bs.ccc.contracting.behavior.FBasicTypeId}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predefined</em>' attribute.
   * @see de.tu_bs.ccc.contracting.behavior.FBasicTypeId
   * @see #setPredefined(FBasicTypeId)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFTypeRef_Predefined()
   * @model
   * @generated
   */
  FBasicTypeId getPredefined();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.FTypeRef#getPredefined <em>Predefined</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predefined</em>' attribute.
   * @see de.tu_bs.ccc.contracting.behavior.FBasicTypeId
   * @see #getPredefined()
   * @generated
   */
  void setPredefined(FBasicTypeId value);

  /**
   * Returns the value of the '<em><b>Derived</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derived</em>' reference.
   * @see #setDerived(FType)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFTypeRef_Derived()
   * @model
   * @generated
   */
  FType getDerived();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.FTypeRef#getDerived <em>Derived</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Derived</em>' reference.
   * @see #getDerived()
   * @generated
   */
  void setDerived(FType value);

  /**
   * Returns the value of the '<em><b>Interval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interval</em>' containment reference.
   * @see #setInterval(FIntegerInterval)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFTypeRef_Interval()
   * @model containment="true"
   * @generated
   */
  FIntegerInterval getInterval();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.FTypeRef#getInterval <em>Interval</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interval</em>' containment reference.
   * @see #getInterval()
   * @generated
   */
  void setInterval(FIntegerInterval value);

} // FTypeRef
