/**
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.behavior;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FUnary Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.FUnaryOperation#getOp <em>Op</em>}</li>
 *   <li>{@link de.tu_bs.ccc.contracting.behavior.FUnaryOperation#getOperand <em>Operand</em>}</li>
 * </ul>
 *
 * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFUnaryOperation()
 * @model
 * @generated
 */
public interface FUnaryOperation extends FExpression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link de.tu_bs.ccc.contracting.behavior.FOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see de.tu_bs.ccc.contracting.behavior.FOperator
   * @see #setOp(FOperator)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFUnaryOperation_Op()
   * @model
   * @generated
   */
  FOperator getOp();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.FUnaryOperation#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see de.tu_bs.ccc.contracting.behavior.FOperator
   * @see #getOp()
   * @generated
   */
  void setOp(FOperator value);

  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference.
   * @see #setOperand(FExpression)
   * @see de.tu_bs.ccc.contracting.behavior.BehaviorPackage#getFUnaryOperation_Operand()
   * @model containment="true"
   * @generated
   */
  FExpression getOperand();

  /**
   * Sets the value of the '{@link de.tu_bs.ccc.contracting.behavior.FUnaryOperation#getOperand <em>Operand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand</em>' containment reference.
   * @see #getOperand()
   * @generated
   */
  void setOperand(FExpression value);

} // FUnaryOperation
