/**
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.ide;

import tu_bs.cs.isf.mapping.ide.AbstractMappingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MappingIdeModule extends AbstractMappingIdeModule {
}
