/*
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMappingScopeProvider extends DelegatingScopeProvider {
}
