/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.serializer;

import com.google.inject.Inject;
import de.tu_bs.ccc.contracting.edl.events.Annotation;
import de.tu_bs.ccc.contracting.edl.events.AnnotationBlock;
import de.tu_bs.ccc.contracting.edl.events.Event;
import de.tu_bs.ccc.contracting.edl.events.EventType;
import de.tu_bs.ccc.contracting.edl.events.EventsPackage;
import de.tu_bs.ccc.contracting.edl.events.Import;
import de.tu_bs.ccc.contracting.edl.events.Model;
import de.tu_bs.ccc.contracting.edl.services.EventsGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class EventsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private EventsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == EventsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case EventsPackage.ANNOTATION:
				sequence_Annotation(context, (Annotation) semanticObject); 
				return; 
			case EventsPackage.ANNOTATION_BLOCK:
				sequence_AnnotationBlock(context, (AnnotationBlock) semanticObject); 
				return; 
			case EventsPackage.EVENT:
				sequence_Event(context, (Event) semanticObject); 
				return; 
			case EventsPackage.EVENT_TYPE:
				sequence_EventType(context, (EventType) semanticObject); 
				return; 
			case EventsPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case EventsPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AnnotationBlock returns AnnotationBlock
	 *
	 * Constraint:
	 *     elements+=Annotation+
	 */
	protected void sequence_AnnotationBlock(ISerializationContext context, AnnotationBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Annotation returns Annotation
	 *
	 * Constraint:
	 *     rawText=ANNOTATION_STRING
	 */
	protected void sequence_Annotation(ISerializationContext context, Annotation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, EventsPackage.Literals.ANNOTATION__RAW_TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, EventsPackage.Literals.ANNOTATION__RAW_TEXT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAnnotationAccess().getRawTextANNOTATION_STRINGTerminalRuleCall_0(), semanticObject.getRawText());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     EventType returns EventType
	 *
	 * Constraint:
	 *     (comment=AnnotationBlock? name=ID? events+=Event events+=Event*)
	 */
	protected void sequence_EventType(ISerializationContext context, EventType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Event returns Event
	 *
	 * Constraint:
	 *     (element=ID default?='default'?)
	 */
	protected void sequence_Event(ISerializationContext context, Event semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Import returns Import
	 *
	 * Constraint:
	 *     (importedNamespace=ImportedFQN? importURI=STRING)
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (name=FQN imports+=Import* eventCollection+=EventType*)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
