/*
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MappingUiModule extends AbstractMappingUiModule {
}
