/*
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MappingStandaloneSetup extends MappingStandaloneSetupGenerated {

	def static void doSetup() {
		new MappingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
