/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class EventsProposalProvider extends AbstractEventsProposalProvider {
}
