/**
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import tu_bs.cs.isf.mapping.ui.AbstractMappingUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MappingUiModule extends AbstractMappingUiModule {
  public MappingUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
