/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.edl.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class EventsValidator extends AbstractEventsValidator {
	
//	public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					EventsPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
