/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.tu_bs.ccc.contracting.ide.contentassist.antlr.internal.InternalBehaviorParser;
import de.tu_bs.ccc.contracting.services.BehaviorGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class BehaviorParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BehaviorGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BehaviorGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEventOnIfAccess().getAlternatives(), "rule__EventOnIf__Alternatives");
			builder.put(grammarAccess.getMethodSignatureAccess().getAlternatives_4_1(), "rule__MethodSignature__Alternatives_4_1");
			builder.put(grammarAccess.getStandardOperationAccess().getAlternatives_7_1(), "rule__StandardOperation__Alternatives_7_1");
			builder.put(grammarAccess.getFEventOnIfAccess().getAlternatives(), "rule__FEventOnIf__Alternatives");
			builder.put(grammarAccess.getFTypeRefAccess().getAlternatives(), "rule__FTypeRef__Alternatives");
			builder.put(grammarAccess.getFIntegerIntervalAccess().getAlternatives_2_1(), "rule__FIntegerInterval__Alternatives_2_1");
			builder.put(grammarAccess.getFIntegerIntervalAccess().getAlternatives_2_3(), "rule__FIntegerInterval__Alternatives_2_3");
			builder.put(grammarAccess.getFTypeAccess().getAlternatives(), "rule__FType__Alternatives");
			builder.put(grammarAccess.getFStructTypeAccess().getAlternatives_5(), "rule__FStructType__Alternatives_5");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
			builder.put(grammarAccess.getSimplePrimaryExpressionAccess().getAlternatives(), "rule__SimplePrimaryExpression__Alternatives");
			builder.put(grammarAccess.getFConstantAccess().getAlternatives(), "rule__FConstant__Alternatives");
			builder.put(grammarAccess.getFTypedElementAccess().getAlternatives(), "rule__FTypedElement__Alternatives");
			builder.put(grammarAccess.getFInitializerAccess().getAlternatives(), "rule__FInitializer__Alternatives");
			builder.put(grammarAccess.getDetailCodeAccess().getAlternatives(), "rule__DetailCode__Alternatives");
			builder.put(grammarAccess.getImportAccess().getAlternatives_1(), "rule__Import__Alternatives_1");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getFBasicTypeIdAccess().getAlternatives(), "rule__FBasicTypeId__Alternatives");
			builder.put(grammarAccess.getOperatorEqualityAccess().getAlternatives(), "rule__OperatorEquality__Alternatives");
			builder.put(grammarAccess.getOperatorRelationalAccess().getAlternatives(), "rule__OperatorRelational__Alternatives");
			builder.put(grammarAccess.getOperatorAdditiveAccess().getAlternatives(), "rule__OperatorAdditive__Alternatives");
			builder.put(grammarAccess.getOperatorMultiplicativeAccess().getAlternatives(), "rule__OperatorMultiplicative__Alternatives");
			builder.put(grammarAccess.getOperatorUnaryAccess().getAlternatives(), "rule__OperatorUnary__Alternatives");
			builder.put(grammarAccess.getBehaviorModelAccess().getGroup(), "rule__BehaviorModel__Group__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup(), "rule__Behavior__Group__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_4(), "rule__Behavior__Group_4__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_6(), "rule__Behavior__Group_6__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_6_2(), "rule__Behavior__Group_6_2__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_7(), "rule__Behavior__Group_7__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_7_2(), "rule__Behavior__Group_7_2__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_8(), "rule__Behavior__Group_8__0");
			builder.put(grammarAccess.getBehaviorAccess().getGroup_8_2(), "rule__Behavior__Group_8_2__0");
			builder.put(grammarAccess.getSignalAccess().getGroup(), "rule__Signal__Group__0");
			builder.put(grammarAccess.getSignalSignatureAccess().getGroup(), "rule__SignalSignature__Group__0");
			builder.put(grammarAccess.getSignalSignatureAccess().getGroup_1(), "rule__SignalSignature__Group_1__0");
			builder.put(grammarAccess.getSignalSignatureAccess().getGroup_1_1(), "rule__SignalSignature__Group_1_1__0");
			builder.put(grammarAccess.getSignalSignatureAccess().getGroup_1_1_1(), "rule__SignalSignature__Group_1_1_1__0");
			builder.put(grammarAccess.getEventBindingAccess().getGroup(), "rule__EventBinding__Group__0");
			builder.put(grammarAccess.getEventOnIfAccess().getGroup_0(), "rule__EventOnIf__Group_0__0");
			builder.put(grammarAccess.getEventOnIfAccess().getGroup_1(), "rule__EventOnIf__Group_1__0");
			builder.put(grammarAccess.getEventOnIfAccess().getGroup_2(), "rule__EventOnIf__Group_2__0");
			builder.put(grammarAccess.getEventOnIfAccess().getGroup_3(), "rule__EventOnIf__Group_3__0");
			builder.put(grammarAccess.getEventOnIfAccess().getGroup_4(), "rule__EventOnIf__Group_4__0");
			builder.put(grammarAccess.getMethodSignatureAccess().getGroup(), "rule__MethodSignature__Group__0");
			builder.put(grammarAccess.getMethodSignatureAccess().getGroup_2(), "rule__MethodSignature__Group_2__0");
			builder.put(grammarAccess.getMethodSignatureAccess().getGroup_2_1(), "rule__MethodSignature__Group_2_1__0");
			builder.put(grammarAccess.getMethodSignatureAccess().getGroup_4(), "rule__MethodSignature__Group_4__0");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1(), "rule__Event__Group_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1_2(), "rule__Event__Group_1_2__0");
			builder.put(grammarAccess.getStandardOperationAccess().getGroup(), "rule__StandardOperation__Group__0");
			builder.put(grammarAccess.getStandardOperationAccess().getGroup_5(), "rule__StandardOperation__Group_5__0");
			builder.put(grammarAccess.getStandardOperationAccess().getGroup_5_1(), "rule__StandardOperation__Group_5_1__0");
			builder.put(grammarAccess.getStandardOperationAccess().getGroup_7(), "rule__StandardOperation__Group_7__0");
			builder.put(grammarAccess.getStandardOperationAccess().getGroup_7_1_1(), "rule__StandardOperation__Group_7_1_1__0");
			builder.put(grammarAccess.getStandardOperationAccess().getGroup_7_1_1_1(), "rule__StandardOperation__Group_7_1_1_1__0");
			builder.put(grammarAccess.getVarDeclAccess().getGroup(), "rule__VarDecl__Group__0");
			builder.put(grammarAccess.getVarDeclAccess().getGroup_3(), "rule__VarDecl__Group_3__0");
			builder.put(grammarAccess.getRefableTypeAccess().getGroup(), "rule__RefableType__Group__0");
			builder.put(grammarAccess.getSpecificationBlockAccess().getGroup(), "rule__SpecificationBlock__Group__0");
			builder.put(grammarAccess.getSpecificationBlockAccess().getGroup_5(), "rule__SpecificationBlock__Group_5__0");
			builder.put(grammarAccess.getContractPairAccess().getGroup(), "rule__ContractPair__Group__0");
			builder.put(grammarAccess.getRequiresAccess().getGroup(), "rule__Requires__Group__0");
			builder.put(grammarAccess.getEnsuresAccess().getGroup(), "rule__Ensures__Group__0");
			builder.put(grammarAccess.getFStateGraphAccess().getGroup(), "rule__FStateGraph__Group__0");
			builder.put(grammarAccess.getFStateAccess().getGroup(), "rule__FState__Group__0");
			builder.put(grammarAccess.getFStateAccess().getGroup_5(), "rule__FState__Group_5__0");
			builder.put(grammarAccess.getFStateAccess().getGroup_6(), "rule__FState__Group_6__0");
			builder.put(grammarAccess.getFStateAccess().getGroup_7(), "rule__FState__Group_7__0");
			builder.put(grammarAccess.getFTransitionAccess().getGroup(), "rule__FTransition__Group__0");
			builder.put(grammarAccess.getFTransitionAccess().getGroup_5(), "rule__FTransition__Group_5__0");
			builder.put(grammarAccess.getFEventOnIfAccess().getGroup_0(), "rule__FEventOnIf__Group_0__0");
			builder.put(grammarAccess.getFEventOnIfAccess().getGroup_1(), "rule__FEventOnIf__Group_1__0");
			builder.put(grammarAccess.getBroadcastAccess().getGroup(), "rule__Broadcast__Group__0");
			builder.put(grammarAccess.getBroadcastAccess().getGroup_2(), "rule__Broadcast__Group_2__0");
			builder.put(grammarAccess.getBroadcastAccess().getGroup_2_2(), "rule__Broadcast__Group_2_2__0");
			builder.put(grammarAccess.getFGuardAccess().getGroup(), "rule__FGuard__Group__0");
			builder.put(grammarAccess.getFIntegerIntervalAccess().getGroup(), "rule__FIntegerInterval__Group__0");
			builder.put(grammarAccess.getFIntegerIntervalAccess().getGroup_2(), "rule__FIntegerInterval__Group_2__0");
			builder.put(grammarAccess.getINTERVAL_BOUNDAccess().getGroup(), "rule__INTERVAL_BOUND__Group__0");
			builder.put(grammarAccess.getFArrayTypeAccess().getGroup(), "rule__FArrayType__Group__0");
			builder.put(grammarAccess.getFTypeDefAccess().getGroup(), "rule__FTypeDef__Group__0");
			builder.put(grammarAccess.getFStructTypeAccess().getGroup(), "rule__FStructType__Group__0");
			builder.put(grammarAccess.getFStructTypeAccess().getGroup_5_0(), "rule__FStructType__Group_5_0__0");
			builder.put(grammarAccess.getFUnionTypeAccess().getGroup(), "rule__FUnionType__Group__0");
			builder.put(grammarAccess.getFUnionTypeAccess().getGroup_5(), "rule__FUnionType__Group_5__0");
			builder.put(grammarAccess.getLogicalOrExpressionAccess().getGroup(), "rule__LogicalOrExpression__Group__0");
			builder.put(grammarAccess.getLogicalOrExpressionAccess().getGroup_1(), "rule__LogicalOrExpression__Group_1__0");
			builder.put(grammarAccess.getLogicalAndExpressionAccess().getGroup(), "rule__LogicalAndExpression__Group__0");
			builder.put(grammarAccess.getLogicalAndExpressionAccess().getGroup_1(), "rule__LogicalAndExpression__Group_1__0");
			builder.put(grammarAccess.getEqualityExpressionAccess().getGroup(), "rule__EqualityExpression__Group__0");
			builder.put(grammarAccess.getEqualityExpressionAccess().getGroup_1(), "rule__EqualityExpression__Group_1__0");
			builder.put(grammarAccess.getRelationalExpressionAccess().getGroup(), "rule__RelationalExpression__Group__0");
			builder.put(grammarAccess.getRelationalExpressionAccess().getGroup_1(), "rule__RelationalExpression__Group_1__0");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getGroup(), "rule__AdditiveExpression__Group__0");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getGroup_1(), "rule__AdditiveExpression__Group_1__0");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getGroup(), "rule__MultiplicativeExpression__Group__0");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1(), "rule__MultiplicativeExpression__Group_1__0");
			builder.put(grammarAccess.getSimplePrimaryExpressionAccess().getGroup_2(), "rule__SimplePrimaryExpression__Group_2__0");
			builder.put(grammarAccess.getFUnaryOperationAccess().getGroup(), "rule__FUnaryOperation__Group__0");
			builder.put(grammarAccess.getFQualifiedElementRefAccess().getGroup(), "rule__FQualifiedElementRef__Group__0");
			builder.put(grammarAccess.getFQualifiedElementRefAccess().getGroup_2(), "rule__FQualifiedElementRef__Group_2__0");
			builder.put(grammarAccess.getFMapTypeAccess().getGroup(), "rule__FMapType__Group__0");
			builder.put(grammarAccess.getFFieldAccess().getGroup(), "rule__FField__Group__0");
			builder.put(grammarAccess.getFFieldAccess().getGroup_2(), "rule__FField__Group_2__0");
			builder.put(grammarAccess.getFDeclarationAccess().getGroup(), "rule__FDeclaration__Group__0");
			builder.put(grammarAccess.getFDeclarationAccess().getGroup_1(), "rule__FDeclaration__Group_1__0");
			builder.put(grammarAccess.getFDeclarationAccess().getGroup_3(), "rule__FDeclaration__Group_3__0");
			builder.put(grammarAccess.getFArgumentAccess().getGroup(), "rule__FArgument__Group__0");
			builder.put(grammarAccess.getFArgumentAccess().getGroup_2(), "rule__FArgument__Group_2__0");
			builder.put(grammarAccess.getFConstantDefAccess().getGroup(), "rule__FConstantDef__Group__0");
			builder.put(grammarAccess.getFConstantDefAccess().getGroup_3(), "rule__FConstantDef__Group_3__0");
			builder.put(grammarAccess.getFCompoundInitializerAccess().getGroup(), "rule__FCompoundInitializer__Group__0");
			builder.put(grammarAccess.getFCompoundInitializerAccess().getGroup_2(), "rule__FCompoundInitializer__Group_2__0");
			builder.put(grammarAccess.getFCompoundInitializerAccess().getGroup_2_1(), "rule__FCompoundInitializer__Group_2_1__0");
			builder.put(grammarAccess.getFFieldInitializerAccess().getGroup(), "rule__FFieldInitializer__Group__0");
			builder.put(grammarAccess.getFBracketInitializerAccess().getGroup(), "rule__FBracketInitializer__Group__0");
			builder.put(grammarAccess.getFBracketInitializerAccess().getGroup_2(), "rule__FBracketInitializer__Group_2__0");
			builder.put(grammarAccess.getFBracketInitializerAccess().getGroup_2_1(), "rule__FBracketInitializer__Group_2_1__0");
			builder.put(grammarAccess.getFElementInitializerAccess().getGroup(), "rule__FElementInitializer__Group__0");
			builder.put(grammarAccess.getFElementInitializerAccess().getGroup_2(), "rule__FElementInitializer__Group_2__0");
			builder.put(grammarAccess.getDetailCodeAccess().getGroup_0(), "rule__DetailCode__Group_0__0");
			builder.put(grammarAccess.getDetailCodeAccess().getGroup_1(), "rule__DetailCode__Group_1__0");
			builder.put(grammarAccess.getAnnotationBlockAccess().getGroup(), "rule__AnnotationBlock__Group__0");
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getImportAccess().getGroup_1_0(), "rule__Import__Group_1_0__0");
			builder.put(grammarAccess.getImportAccess().getGroup_3(), "rule__Import__Group_3__0");
			builder.put(grammarAccess.getImportedFQNAccess().getGroup(), "rule__ImportedFQN__Group__0");
			builder.put(grammarAccess.getImportedFQNAccess().getGroup_1(), "rule__ImportedFQN__Group_1__0");
			builder.put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
			builder.put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
			builder.put(grammarAccess.getID_WITH_SELECTORAccess().getGroup(), "rule__ID_WITH_SELECTOR__Group__0");
			builder.put(grammarAccess.getID_WITH_SELECTORAccess().getGroup_1(), "rule__ID_WITH_SELECTOR__Group_1__0");
			builder.put(grammarAccess.getBehaviorModelAccess().getNameAssignment_2(), "rule__BehaviorModel__NameAssignment_2");
			builder.put(grammarAccess.getBehaviorModelAccess().getImportsAssignment_3(), "rule__BehaviorModel__ImportsAssignment_3");
			builder.put(grammarAccess.getBehaviorModelAccess().getBehaviorsAssignment_4(), "rule__BehaviorModel__BehaviorsAssignment_4");
			builder.put(grammarAccess.getBehaviorAccess().getCommentAssignment_1(), "rule__Behavior__CommentAssignment_1");
			builder.put(grammarAccess.getBehaviorAccess().getNameAssignment_3(), "rule__Behavior__NameAssignment_3");
			builder.put(grammarAccess.getBehaviorAccess().getComponentNameAssignment_4_1(), "rule__Behavior__ComponentNameAssignment_4_1");
			builder.put(grammarAccess.getBehaviorAccess().getVariablesAssignment_6_2_0(), "rule__Behavior__VariablesAssignment_6_2_0");
			builder.put(grammarAccess.getBehaviorAccess().getEventsAssignment_7_2_0(), "rule__Behavior__EventsAssignment_7_2_0");
			builder.put(grammarAccess.getBehaviorAccess().getSignalsAssignment_8_2_0(), "rule__Behavior__SignalsAssignment_8_2_0");
			builder.put(grammarAccess.getBehaviorAccess().getOperationsAssignment_9(), "rule__Behavior__OperationsAssignment_9");
			builder.put(grammarAccess.getBehaviorAccess().getNameAssignment_11(), "rule__Behavior__NameAssignment_11");
			builder.put(grammarAccess.getBehaviorAccess().getStateGraphsAssignment_12(), "rule__Behavior__StateGraphsAssignment_12");
			builder.put(grammarAccess.getSignalAccess().getCommentAssignment_1(), "rule__Signal__CommentAssignment_1");
			builder.put(grammarAccess.getSignalAccess().getSignalAssignment_2(), "rule__Signal__SignalAssignment_2");
			builder.put(grammarAccess.getSignalSignatureAccess().getNameAssignment_0(), "rule__SignalSignature__NameAssignment_0");
			builder.put(grammarAccess.getSignalSignatureAccess().getArgumentsAssignment_1_1_0(), "rule__SignalSignature__ArgumentsAssignment_1_1_0");
			builder.put(grammarAccess.getSignalSignatureAccess().getArgumentsAssignment_1_1_1_1(), "rule__SignalSignature__ArgumentsAssignment_1_1_1_1");
			builder.put(grammarAccess.getEventBindingAccess().getCommentAssignment_1(), "rule__EventBinding__CommentAssignment_1");
			builder.put(grammarAccess.getEventBindingAccess().getTriggerAssignment_3(), "rule__EventBinding__TriggerAssignment_3");
			builder.put(grammarAccess.getEventBindingAccess().getToAssignment_5(), "rule__EventBinding__ToAssignment_5");
			builder.put(grammarAccess.getEventTriggerAccess().getEventAssignment(), "rule__EventTrigger__EventAssignment");
			builder.put(grammarAccess.getEventOnIfAccess().getFreqAssignment_0_1(), "rule__EventOnIf__FreqAssignment_0_1");
			builder.put(grammarAccess.getEventOnIfAccess().getConditionAssignment_1_1(), "rule__EventOnIf__ConditionAssignment_1_1");
			builder.put(grammarAccess.getEventOnIfAccess().getCallAssignment_2_1(), "rule__EventOnIf__CallAssignment_2_1");
			builder.put(grammarAccess.getEventOnIfAccess().getEventAssignment_3_1(), "rule__EventOnIf__EventAssignment_3_1");
			builder.put(grammarAccess.getEventOnIfAccess().getSignalAssignment_4_1(), "rule__EventOnIf__SignalAssignment_4_1");
			builder.put(grammarAccess.getMethodSignatureAccess().getNameAssignment_0(), "rule__MethodSignature__NameAssignment_0");
			builder.put(grammarAccess.getMethodSignatureAccess().getArgumentsAssignment_2_0(), "rule__MethodSignature__ArgumentsAssignment_2_0");
			builder.put(grammarAccess.getMethodSignatureAccess().getArgumentsAssignment_2_1_1(), "rule__MethodSignature__ArgumentsAssignment_2_1_1");
			builder.put(grammarAccess.getMethodSignatureAccess().getReturnTypeAssignment_4_1_1(), "rule__MethodSignature__ReturnTypeAssignment_4_1_1");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_0(), "rule__Event__NameAssignment_0");
			builder.put(grammarAccess.getEventAccess().getArgumentsAssignment_1_1(), "rule__Event__ArgumentsAssignment_1_1");
			builder.put(grammarAccess.getEventAccess().getArgumentsAssignment_1_2_1(), "rule__Event__ArgumentsAssignment_1_2_1");
			builder.put(grammarAccess.getStandardOperationAccess().getCommentAssignment_0(), "rule__StandardOperation__CommentAssignment_0");
			builder.put(grammarAccess.getStandardOperationAccess().getOverrideAssignment_1(), "rule__StandardOperation__OverrideAssignment_1");
			builder.put(grammarAccess.getStandardOperationAccess().getNameAssignment_3(), "rule__StandardOperation__NameAssignment_3");
			builder.put(grammarAccess.getStandardOperationAccess().getArgumentsAssignment_5_0(), "rule__StandardOperation__ArgumentsAssignment_5_0");
			builder.put(grammarAccess.getStandardOperationAccess().getArgumentsAssignment_5_1_1(), "rule__StandardOperation__ArgumentsAssignment_5_1_1");
			builder.put(grammarAccess.getStandardOperationAccess().getReturnTypeAssignment_7_1_1_0(), "rule__StandardOperation__ReturnTypeAssignment_7_1_1_0");
			builder.put(grammarAccess.getStandardOperationAccess().getArrayAssignment_7_1_1_1_0(), "rule__StandardOperation__ArrayAssignment_7_1_1_1_0");
			builder.put(grammarAccess.getStandardOperationAccess().getContractAssignment_9(), "rule__StandardOperation__ContractAssignment_9");
			builder.put(grammarAccess.getStandardOperationAccess().getDetailCodeAssignment_10(), "rule__StandardOperation__DetailCodeAssignment_10");
			builder.put(grammarAccess.getVarDeclAccess().getNameAssignment_0(), "rule__VarDecl__NameAssignment_0");
			builder.put(grammarAccess.getVarDeclAccess().getRefTypeAssignment_2(), "rule__VarDecl__RefTypeAssignment_2");
			builder.put(grammarAccess.getVarDeclAccess().getArrayAssignment_3_0(), "rule__VarDecl__ArrayAssignment_3_0");
			builder.put(grammarAccess.getVarDeclAccess().getVarargsAssignment_4(), "rule__VarDecl__VarargsAssignment_4");
			builder.put(grammarAccess.getRefableTypeAccess().getTypeAssignment_0(), "rule__RefableType__TypeAssignment_0");
			builder.put(grammarAccess.getRefableTypeAccess().getRefAssignment_1(), "rule__RefableType__RefAssignment_1");
			builder.put(grammarAccess.getSpecificationBlockAccess().getCommentAssignment_1(), "rule__SpecificationBlock__CommentAssignment_1");
			builder.put(grammarAccess.getSpecificationBlockAccess().getContractsAssignment_4(), "rule__SpecificationBlock__ContractsAssignment_4");
			builder.put(grammarAccess.getSpecificationBlockAccess().getContractsAssignment_5_1(), "rule__SpecificationBlock__ContractsAssignment_5_1");
			builder.put(grammarAccess.getContractPairAccess().getReqAssignment_1(), "rule__ContractPair__ReqAssignment_1");
			builder.put(grammarAccess.getContractPairAccess().getEnsAssignment_2(), "rule__ContractPair__EnsAssignment_2");
			builder.put(grammarAccess.getRequiresAccess().getExprAssignment_2(), "rule__Requires__ExprAssignment_2");
			builder.put(grammarAccess.getEnsuresAccess().getExprAssignment_2(), "rule__Ensures__ExprAssignment_2");
			builder.put(grammarAccess.getFStateGraphAccess().getInitialAssignment_3(), "rule__FStateGraph__InitialAssignment_3");
			builder.put(grammarAccess.getFStateGraphAccess().getStatesAssignment_4(), "rule__FStateGraph__StatesAssignment_4");
			builder.put(grammarAccess.getFStateAccess().getCommentAssignment_1(), "rule__FState__CommentAssignment_1");
			builder.put(grammarAccess.getFStateAccess().getNameAssignment_3(), "rule__FState__NameAssignment_3");
			builder.put(grammarAccess.getFStateAccess().getEntryActionAssignment_5_2(), "rule__FState__EntryActionAssignment_5_2");
			builder.put(grammarAccess.getFStateAccess().getBroadcastEntryAssignment_5_3(), "rule__FState__BroadcastEntryAssignment_5_3");
			builder.put(grammarAccess.getFStateAccess().getExitActionAssignment_6_2(), "rule__FState__ExitActionAssignment_6_2");
			builder.put(grammarAccess.getFStateAccess().getBroadcastExitAssignment_6_3(), "rule__FState__BroadcastExitAssignment_6_3");
			builder.put(grammarAccess.getFStateAccess().getDoActionAssignment_7_2(), "rule__FState__DoActionAssignment_7_2");
			builder.put(grammarAccess.getFStateAccess().getBoradcastDoAssignment_7_3(), "rule__FState__BoradcastDoAssignment_7_3");
			builder.put(grammarAccess.getFStateAccess().getTransitionsAssignment_8(), "rule__FState__TransitionsAssignment_8");
			builder.put(grammarAccess.getFTransitionAccess().getTriggerAssignment_1(), "rule__FTransition__TriggerAssignment_1");
			builder.put(grammarAccess.getFTransitionAccess().getGuardAssignment_2(), "rule__FTransition__GuardAssignment_2");
			builder.put(grammarAccess.getFTransitionAccess().getToAssignment_4(), "rule__FTransition__ToAssignment_4");
			builder.put(grammarAccess.getFTransitionAccess().getActionAssignment_5_1(), "rule__FTransition__ActionAssignment_5_1");
			builder.put(grammarAccess.getFTransitionAccess().getBroadcastAssignment_5_2(), "rule__FTransition__BroadcastAssignment_5_2");
			builder.put(grammarAccess.getFTriggerAccess().getEventAssignment(), "rule__FTrigger__EventAssignment");
			builder.put(grammarAccess.getFEventOnIfAccess().getNameAssignment_1_1(), "rule__FEventOnIf__NameAssignment_1_1");
			builder.put(grammarAccess.getBroadcastAccess().getSignalAssignment_1(), "rule__Broadcast__SignalAssignment_1");
			builder.put(grammarAccess.getBroadcastAccess().getArgumentsAssignment_2_1(), "rule__Broadcast__ArgumentsAssignment_2_1");
			builder.put(grammarAccess.getBroadcastAccess().getArgumentsAssignment_2_2_1(), "rule__Broadcast__ArgumentsAssignment_2_2_1");
			builder.put(grammarAccess.getFGuardAccess().getConditionAssignment_1(), "rule__FGuard__ConditionAssignment_1");
			builder.put(grammarAccess.getFTypeRefAccess().getPredefinedAssignment_0(), "rule__FTypeRef__PredefinedAssignment_0");
			builder.put(grammarAccess.getFTypeRefAccess().getDerivedAssignment_1(), "rule__FTypeRef__DerivedAssignment_1");
			builder.put(grammarAccess.getFTypeRefAccess().getIntervalAssignment_2(), "rule__FTypeRef__IntervalAssignment_2");
			builder.put(grammarAccess.getFIntegerIntervalAccess().getLowerBoundAssignment_2_1_0(), "rule__FIntegerInterval__LowerBoundAssignment_2_1_0");
			builder.put(grammarAccess.getFIntegerIntervalAccess().getUpperBoundAssignment_2_3_0(), "rule__FIntegerInterval__UpperBoundAssignment_2_3_0");
			builder.put(grammarAccess.getFArrayTypeAccess().getCommentAssignment_1(), "rule__FArrayType__CommentAssignment_1");
			builder.put(grammarAccess.getFArrayTypeAccess().getPublicAssignment_2(), "rule__FArrayType__PublicAssignment_2");
			builder.put(grammarAccess.getFArrayTypeAccess().getNameAssignment_4(), "rule__FArrayType__NameAssignment_4");
			builder.put(grammarAccess.getFArrayTypeAccess().getElementTypeAssignment_6(), "rule__FArrayType__ElementTypeAssignment_6");
			builder.put(grammarAccess.getFTypeDefAccess().getCommentAssignment_1(), "rule__FTypeDef__CommentAssignment_1");
			builder.put(grammarAccess.getFTypeDefAccess().getPublicAssignment_2(), "rule__FTypeDef__PublicAssignment_2");
			builder.put(grammarAccess.getFTypeDefAccess().getNameAssignment_4(), "rule__FTypeDef__NameAssignment_4");
			builder.put(grammarAccess.getFTypeDefAccess().getActualTypeAssignment_6(), "rule__FTypeDef__ActualTypeAssignment_6");
			builder.put(grammarAccess.getFStructTypeAccess().getCommentAssignment_1(), "rule__FStructType__CommentAssignment_1");
			builder.put(grammarAccess.getFStructTypeAccess().getPublicAssignment_2(), "rule__FStructType__PublicAssignment_2");
			builder.put(grammarAccess.getFStructTypeAccess().getNameAssignment_4(), "rule__FStructType__NameAssignment_4");
			builder.put(grammarAccess.getFStructTypeAccess().getBaseAssignment_5_0_1(), "rule__FStructType__BaseAssignment_5_0_1");
			builder.put(grammarAccess.getFStructTypeAccess().getPolymorphicAssignment_5_1(), "rule__FStructType__PolymorphicAssignment_5_1");
			builder.put(grammarAccess.getFStructTypeAccess().getElementsAssignment_7(), "rule__FStructType__ElementsAssignment_7");
			builder.put(grammarAccess.getFUnionTypeAccess().getCommentAssignment_1(), "rule__FUnionType__CommentAssignment_1");
			builder.put(grammarAccess.getFUnionTypeAccess().getPublicAssignment_2(), "rule__FUnionType__PublicAssignment_2");
			builder.put(grammarAccess.getFUnionTypeAccess().getNameAssignment_4(), "rule__FUnionType__NameAssignment_4");
			builder.put(grammarAccess.getFUnionTypeAccess().getBaseAssignment_5_1(), "rule__FUnionType__BaseAssignment_5_1");
			builder.put(grammarAccess.getFUnionTypeAccess().getElementsAssignment_7(), "rule__FUnionType__ElementsAssignment_7");
			builder.put(grammarAccess.getLogicalOrExpressionAccess().getOpAssignment_1_1(), "rule__LogicalOrExpression__OpAssignment_1_1");
			builder.put(grammarAccess.getLogicalOrExpressionAccess().getRightAssignment_1_2(), "rule__LogicalOrExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getLogicalAndExpressionAccess().getOpAssignment_1_1(), "rule__LogicalAndExpression__OpAssignment_1_1");
			builder.put(grammarAccess.getLogicalAndExpressionAccess().getRightAssignment_1_2(), "rule__LogicalAndExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getEqualityExpressionAccess().getOpAssignment_1_1(), "rule__EqualityExpression__OpAssignment_1_1");
			builder.put(grammarAccess.getEqualityExpressionAccess().getRightAssignment_1_2(), "rule__EqualityExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getRelationalExpressionAccess().getOpAssignment_1_1(), "rule__RelationalExpression__OpAssignment_1_1");
			builder.put(grammarAccess.getRelationalExpressionAccess().getRightAssignment_1_2(), "rule__RelationalExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getOpAssignment_1_1(), "rule__AdditiveExpression__OpAssignment_1_1");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getRightAssignment_1_2(), "rule__AdditiveExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getOpAssignment_1_1(), "rule__MultiplicativeExpression__OpAssignment_1_1");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getRightAssignment_1_2(), "rule__MultiplicativeExpression__RightAssignment_1_2");
			builder.put(grammarAccess.getFUnaryOperationAccess().getOpAssignment_1(), "rule__FUnaryOperation__OpAssignment_1");
			builder.put(grammarAccess.getFUnaryOperationAccess().getOperandAssignment_2(), "rule__FUnaryOperation__OperandAssignment_2");
			builder.put(grammarAccess.getFQualifiedElementRefAccess().getElementAssignment_1(), "rule__FQualifiedElementRef__ElementAssignment_1");
			builder.put(grammarAccess.getFQualifiedElementRefAccess().getFieldAssignment_2_2(), "rule__FQualifiedElementRef__FieldAssignment_2_2");
			builder.put(grammarAccess.getFDoubleConstantAccess().getValAssignment(), "rule__FDoubleConstant__ValAssignment");
			builder.put(grammarAccess.getFFloatConstantAccess().getValAssignment(), "rule__FFloatConstant__ValAssignment");
			builder.put(grammarAccess.getFIntegerConstantAccess().getValAssignment(), "rule__FIntegerConstant__ValAssignment");
			builder.put(grammarAccess.getFBooleanConstantAccess().getValAssignment(), "rule__FBooleanConstant__ValAssignment");
			builder.put(grammarAccess.getFStringConstantAccess().getValAssignment(), "rule__FStringConstant__ValAssignment");
			builder.put(grammarAccess.getFMapTypeAccess().getCommentAssignment_1(), "rule__FMapType__CommentAssignment_1");
			builder.put(grammarAccess.getFMapTypeAccess().getPublicAssignment_2(), "rule__FMapType__PublicAssignment_2");
			builder.put(grammarAccess.getFMapTypeAccess().getNameAssignment_4(), "rule__FMapType__NameAssignment_4");
			builder.put(grammarAccess.getFMapTypeAccess().getKeyTypeAssignment_6(), "rule__FMapType__KeyTypeAssignment_6");
			builder.put(grammarAccess.getFMapTypeAccess().getValueTypeAssignment_8(), "rule__FMapType__ValueTypeAssignment_8");
			builder.put(grammarAccess.getFFieldAccess().getCommentAssignment_0(), "rule__FField__CommentAssignment_0");
			builder.put(grammarAccess.getFFieldAccess().getTypeAssignment_1(), "rule__FField__TypeAssignment_1");
			builder.put(grammarAccess.getFFieldAccess().getArrayAssignment_2_0(), "rule__FField__ArrayAssignment_2_0");
			builder.put(grammarAccess.getFFieldAccess().getNameAssignment_3(), "rule__FField__NameAssignment_3");
			builder.put(grammarAccess.getFDeclarationAccess().getTypeAssignment_0(), "rule__FDeclaration__TypeAssignment_0");
			builder.put(grammarAccess.getFDeclarationAccess().getArrayAssignment_1_0(), "rule__FDeclaration__ArrayAssignment_1_0");
			builder.put(grammarAccess.getFDeclarationAccess().getNameAssignment_2(), "rule__FDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getFDeclarationAccess().getRhsAssignment_3_1(), "rule__FDeclaration__RhsAssignment_3_1");
			builder.put(grammarAccess.getFArgumentAccess().getCommentAssignment_0(), "rule__FArgument__CommentAssignment_0");
			builder.put(grammarAccess.getFArgumentAccess().getTypeAssignment_1(), "rule__FArgument__TypeAssignment_1");
			builder.put(grammarAccess.getFArgumentAccess().getArrayAssignment_2_0(), "rule__FArgument__ArrayAssignment_2_0");
			builder.put(grammarAccess.getFArgumentAccess().getNameAssignment_3(), "rule__FArgument__NameAssignment_3");
			builder.put(grammarAccess.getFConstantDefAccess().getCommentAssignment_0(), "rule__FConstantDef__CommentAssignment_0");
			builder.put(grammarAccess.getFConstantDefAccess().getTypeAssignment_2(), "rule__FConstantDef__TypeAssignment_2");
			builder.put(grammarAccess.getFConstantDefAccess().getArrayAssignment_3_0(), "rule__FConstantDef__ArrayAssignment_3_0");
			builder.put(grammarAccess.getFConstantDefAccess().getNameAssignment_4(), "rule__FConstantDef__NameAssignment_4");
			builder.put(grammarAccess.getFConstantDefAccess().getRhsAssignment_6(), "rule__FConstantDef__RhsAssignment_6");
			builder.put(grammarAccess.getFCompoundInitializerAccess().getElementsAssignment_2_0(), "rule__FCompoundInitializer__ElementsAssignment_2_0");
			builder.put(grammarAccess.getFCompoundInitializerAccess().getElementsAssignment_2_1_1(), "rule__FCompoundInitializer__ElementsAssignment_2_1_1");
			builder.put(grammarAccess.getFFieldInitializerAccess().getElementAssignment_0(), "rule__FFieldInitializer__ElementAssignment_0");
			builder.put(grammarAccess.getFFieldInitializerAccess().getValueAssignment_2(), "rule__FFieldInitializer__ValueAssignment_2");
			builder.put(grammarAccess.getFBracketInitializerAccess().getElementsAssignment_2_0(), "rule__FBracketInitializer__ElementsAssignment_2_0");
			builder.put(grammarAccess.getFBracketInitializerAccess().getElementsAssignment_2_1_1(), "rule__FBracketInitializer__ElementsAssignment_2_1_1");
			builder.put(grammarAccess.getFElementInitializerAccess().getFirstAssignment_1(), "rule__FElementInitializer__FirstAssignment_1");
			builder.put(grammarAccess.getFElementInitializerAccess().getSecondAssignment_2_1(), "rule__FElementInitializer__SecondAssignment_2_1");
			builder.put(grammarAccess.getDetailCodeAccess().getLinesAssignment_0_1(), "rule__DetailCode__LinesAssignment_0_1");
			builder.put(grammarAccess.getDetailCodeAccess().getUsedAssignment_1_0(), "rule__DetailCode__UsedAssignment_1_0");
			builder.put(grammarAccess.getDetailCodeAccess().getLinesAssignment_1_1(), "rule__DetailCode__LinesAssignment_1_1");
			builder.put(grammarAccess.getAnnotationBlockAccess().getElementsAssignment_1(), "rule__AnnotationBlock__ElementsAssignment_1");
			builder.put(grammarAccess.getAnnotationAccess().getRawTextAssignment(), "rule__Annotation__RawTextAssignment");
			builder.put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1_0_0(), "rule__Import__ImportedNamespaceAssignment_1_0_0");
			builder.put(grammarAccess.getImportAccess().getImportURIAssignment_2(), "rule__Import__ImportURIAssignment_2");
			builder.put(grammarAccess.getImportAccess().getAliasAssignment_3_1(), "rule__Import__AliasAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BehaviorGrammarAccess grammarAccess;

	@Override
	protected InternalBehaviorParser createParser() {
		InternalBehaviorParser result = new InternalBehaviorParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BehaviorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BehaviorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
