/*
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import tu_bs.cs.isf.mapping.parser.antlr.internal.InternalMappingParser;
import tu_bs.cs.isf.mapping.services.MappingGrammarAccess;

public class MappingParser extends AbstractAntlrParser {

	@Inject
	private MappingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMappingParser createParser(XtextTokenStream stream) {
		return new InternalMappingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MappingModel";
	}

	public MappingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MappingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
