/**
 * generated by Xtext 2.15.0
 */
package tu_bs.cs.isf.mapping;

import tu_bs.cs.isf.mapping.AbstractMappingRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MappingRuntimeModule extends AbstractMappingRuntimeModule {
}
