/*
 * generated by Xtext 2.20.0
 */
package de.tu_bs.ccc.contracting.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.tu_bs.ccc.contracting.BehaviorRuntimeModule;
import de.tu_bs.ccc.contracting.BehaviorStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BehaviorIdeSetup extends BehaviorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BehaviorRuntimeModule(), new BehaviorIdeModule()));
	}
	
}
